name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Clean
      run: make clean

    - name: Build module
      run: make

    - name: Build device tree
      run: make dts
